import Sidebar from '@/components/layout/sidebar';
import type { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function AdminLayout({ children }: { children: React.ReactNode; }) {
    return (
        <section className="bg-neutral-bege-100 min-h-screen h-auto w-screen flex flex-row">
            <Sidebar />
            <div id="content" className="p-7 w-full">
                {children}
            </div>
        </section>
    );
}
